number = set()
a : int=(input("enter your 1 number: "))
number.add(int(a))
b : int=(input("enter your 2 number: "))
number.add(int(b))
c : int=(input("enter your 3 number: "))
number.add(int(c))
d : int=(input("enter your 4 number: "))
number.add(int(d))
e : int=(input("enter your 5 number: "))
number.add(int(e))
f : int=(input("enter your 6 number: "))
number.add(int(f))
g : int=(input("enter your 7 number: "))
number.add(int(g))
h : int=(input("enter your 8 number: "))

print(number)

