word ={
    "kitab": "book",
    "darakht": "tree",
    "pani": "water",
    "mohabbat": "love",
    "zindagi": "life",
    "ghar": "home",
    "roti": "bread",
    "dost": "friend",
    "maa": "mother",
    "baap": "father",
    "bhai": "brother",
    "behan": "sister",
    "safar": "journey",
    "khushi": "happiness",
    "gham": "sadness",
    "aankh": "eye",
    "kaam": "work",
    "khaana": "food",
    "neend": "sleep",
    "pyaar": "affection",
    "sach": "truth",
    "jhoot": "lie",
    "safar": "travel",
    "muskurahat": "smile",
    "dil": "heart",
    "zuban": "tongue",
    "sooraj": "sun",
    "chaand": "moon",
    "taare": "stars",
    "hawaa": "wind",
    "barish": "rain",
    "duniya": "world",
    "insaan": "human",
    "zakhm": "wound",
    "dard": "pain",
    "ilaj": "treatment",
    "dawai": "medicine",
    "doctor": "doctor",
    "school": "school",
    "ustad": "teacher",
    "talib": "student",
    "likhna": "write",
    "parhna": "read",
    "bolna": "speak",
    "sunna": "listen",
    "dekhna": "see",
    "samajhna": "understand",
    "chalna": "walk",
    "dourna": "run",
    "baithna": "sit",
    "uthna": "get up",
    "aana": "come",
    "jana": "go",
    "sochna": "think",
    "karna": "do",
    "banana": "make",
    "tootna": "break",
    "jodna": "fix",
    "rang": "color",
    "kala": "black",
    "safed": "white",
    "laal": "red",
    "peela": "yellow",
    "hara": "green",
    "neela": "blue",
    "naram": "soft",
    "sakht": "hard",
    "bara": "big",
    "chhota": "small",
    "tez": "fast",
    "ahista": "slow",
    "acha": "good",
    "bura": "bad",
    "thanda": "cold",
    "garam": "hot",
    "sasta": "cheap",
    "mehnga": "expensive",
    "naya": "new",
    "purana": "old",
    "aasaan": "easy",
    "mushkil": "difficult",
    "mazedaar": "tasty",
    "bezaar": "boring",
    "shor": "noise",
    "khamoshi": "silence",
    "jaanwar": "animal",
    "insaniat": "humanity",
    "khaali": "empty",
    "bharpoor": "full",
    "mushkuraana": "to smile",
    "rona": "to cry",
    "soona": "to sleep",
    "jagna": "to wake",
    "lena": "to take",
    "dena": "to give",
    "padhna": "to read",
    "likhna": "to write"


}

words = input("read the dictionay and then enter the word that you are convert from urdu to english: ")

print(word[words])